camel:
  springboot:
    # The Camel context name
    name: CamelRestSql
  component:
    quartz2:
      enabled: true
      enable-jmx: false
      resolve-property-placeholders: true
      properties-file: quartz2.properties

    servlet:
      mapping:
        enabled: true
        context-path: /camel-rest-sql/*

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

spring:
  # Spring JDBC configuration
#  datasource:
#     Let Spring Boot auto-configure an embedded HSQL database
#    url:

# H2
  h2:
    console:
      enabled: false
      path: h2
  datasource:
    # Let Spring Boot auto-configure an embedded HSQL database
    url: jdbc:mysql://127.0.0.1:3306/sampledb
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver

# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s

driverclassname: org.h2.Driver